# clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sibyl-binding
subjects:
- kind: ServiceAccount
  name: {{ include "sibyl.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }} # Namespace where your app runs
roleRef:
  kind: ClusterRole
  name: sibyl-editor-role
  apiGroup: rbac.authorization.k8s.io