{{- if not .Values.slack.useExistingSecret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sibyl.fullname" . }}-slack-credentials
stringData:
  SLACK_CHANNEL: {{ .Values.slack.channel }}
  SLACK_BOT_TOKEN: {{ .Values.slack.botToken }}
{{- end }}
