name: Build and Push Docker Image

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  # python-unit-tests:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v4
        
  #     - name: Set up Python with uv
  #       # This action handles installing uv and can set the Python version
  #       uses: astral-sh/setup-uv@v7 # Use the latest version
  #       with:
  #         # Optionally specify a Python version or let uv read it from .python-version or pyproject.toml
  #         python-version: '3.11' 
  #         # Enable caching for faster dependency resolution on subsequent runs
  #         enable-cache: true

  #     - name: Install Dependencies
  #       run: uv sync
  
  #     - name: Run PyTests
  #       run: uv run pytest

  #     - name: Upload Pytest JUnit Artifact
  #       uses: actions/upload-artifact@v4
  #       if: always()
  #       with:
  #         name: pytest-junit-report
  #         path: reports/junit/unit.xml
            
  #     # Upload the Coverage XML file for external tools (e.g., Codecov, SonarQube)
  #     - name: Upload Coverage XML Artifact
  #       uses: actions/upload-artifact@v4
  #       if: always()
  #       with:
  #         name: pytest-coverage-xml-report
  #         path: reports/coverage/coverage.xml

  helm-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
    
      - name: Run Helm Unit Tests and Generate Junit Report
        run: |
          mkdir -p reports/junit/helm
          RUNNER_UID=$(id -u)
          RUNNER_GID=$(id -g)
          # The command now includes '-o test-output.xml -t junit'
          # to generate the JUnit-style report in the current directory (which is mounted).
          docker run --rm --user $RUNNER_UID:$RUNNER_GID -v $(pwd):/apps helmunittest/helm-unittest:3.11.1-0.3.0 -o reports/junit/helm/unit.xml -t junit ./charts/sibyl
        id: helm_tests

      - name: Upload Helm Test Results Artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: helm-unittest-results
          path: reports/junit/helm/unit.xml

  build-and-publish-docker:
    if: success()
    needs: [helm-unit-tests]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
      attestations: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract version from pyproject.toml
        id: get_version
        run: |
          VERSION=$(grep '^version' pyproject.toml | head -n1 | cut -d '"' -f2)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Extract medata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4.3.0
        with:
            images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
            tags: |
                type=schedule
                type=semver,pattern={{version}}
                type=semver,pattern={{major}}.{{minor}}
                type=semver,pattern={{major}}
                type=ref,event=branch
                type=ref,event=pr
                type=ref,event=tag
                type=sha
            labels: |
                org.opencontainers.image.title=com.projectterris.sibyl
                org.opencontainers.image.description=Sibyl
                org.opencontainers.image.vendor=project-terris
                com.project-terris.sibyl.image.pyprojectversion=${{ steps.get_version.outputs.version }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4.0.0
        id: push
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}